### ISSUE TITLE
error with the white paper example

### ISSUE THREAD

**Issue by aksakalli** [tomtom-international/openlr#1]
In the whitepaper, section "13.1.3. Binary location reference" contains a base64 encoded string `CwRbWyNG9RpsCQCb/jsbtAT/6/+jK1lE` with a result such as:

![Screenshot from 2019-07-26 20-00-48](https://user-images.githubusercontent.com/1939193/61972067-ed488a00-afe0-11e9-8ed5-509987f59a80.png)

if you run the same example in the referance implementation, it gives a drastically different result.

```java
LocationReference lr = new LocationReferenceBinaryImpl("grid",
                new ByteArray("CwRbWyNG9RpsCQCb/jsbtAT/6/+jK1lE"));
OpenLRBinaryDecoder decoder = new OpenLRBinaryDecoder();
RawLocationReference rawLocRef = decoder.decodeData(lr);
```

Result:
```
id: line
locType: LINE_LOCATION 
points: [
  lon: 6.126819848985067 lat: 49.608517884971576 frc: FRC_3 fow: MULTIPLE_CARRIAGEWAY bearing: 140.625 dnp: 557 lfrcnp: FRC_3 isLast: false,
  
  lon: 6.128369849029585 lat: 49.603987884936856 frc: FRC_3 fow: SINGLE_CARRIAGEWAY bearing: 230.625 dnp: 264 lfrcnp: FRC_5 isLast: false,
  
  lon: 6.128159849031252 lat: 49.60305788495671 frc: FRC_5 fow: SINGLE_CARRIAGEWAY bearing: 286.875 dnp: 0 lfrcnp: FRC_7 isLast: true
]
offsets:
version: 3
posOff: 26.757812
negOff: 0.0
```

the longitude is largely different.

**Comment by BonyBabu** [comment]
![absoluteformat](https://user-images.githubusercontent.com/37437260/64593078-ac001400-d3ad-11e9-8f82-18b66c58e97c.png)

**Comment by aksakalli** [comment]
Oh true! I missed out that the accuracy of 5th digit is really high. I should have remembered [xkcd](https://xkcd.com/2170/). Thank you.

```
d((6.12683, 49.60851), (6.126819848985067, 49.608517884971576)) = 1.14 meters
d((6.12838, 49.60398), (6.128369849029585, 49.603987884936856)) = 1.14 meters
d((6.12817, 49.60305), (6.128159849031252, 49.60305788495671)) = 1.14 meters
```
